apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: 039612866426.dkr.ecr.ap-south-1.amazonaws.com/nagp:latest
          ports:
            - containerPort: 9091
          env:
            - name: JDBC_USER
              valueFrom:
                configMapKeyRef:
                  name: product-service-config
                  key: JDBC_USER
            - name: JDBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: product-service-secret
                  key: JDBC_PASSWORD

---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: default
spec:
  selector:
    app: product-service
  ports:
    - protocol: TCP
      port: 9091
      targetPort: 9091
  type: ClusterIP

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: product-service
spec:
  hosts:
    - "*"
  gateways:
    - istio-ingressgateway
  http:
    - match:
        - uri:
            prefix: /products
      route:
        - destination:
            host: product-service.default.svc.cluster.local
            port:
              number: 9091
