apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: 039612866426.dkr.ecr.us-west-2.amazonaws.com/nagp:latest
          ports:
            - containerPort: 9091

---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: webcart
spec:
  selector:
    app: product-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9091
  type: NodePort
